refactor: remove peer dependencies from package-lock.json and update service worker script
- Removed unnecessary "peer" flags from several dependencies in package-lock.json to streamline the dependency tree.
- Updated the service worker script to improve caching logic and added error handling for fetch requests.
- Deleted the unused API route for fetching secrets from the Baxter client.
- Added a source map for the updated service worker script for better debugging.

diff --git a/.github/workflows/deploy_app.yml b/.github/workflows/deploy_app.yml
--- a/.github/workflows/deploy_app.yml
+++ b/.github/workflows/deploy_app.yml
@@ -2,7 +2,7 @@ name: CI/CD Pipeline a VPS
 
 on:
   push:
-    branches: [ "develop" ] # Se ejecuta al hacer push a la rama develop
+    branches: ['develop'] # Se ejecuta al hacer push a la rama develop
 
 env:
   IMAGE_NAME: anahuarket
@@ -21,38 +21,38 @@ jobs:
       id-token: write
 
     steps:
-    - name: Checkout del código
-      uses: actions/checkout@v4
-    
-    - name: Login en GitHub Container Registry
-      uses: docker/login-action@v3
-      with:
-        registry: ghcr.io
-        username: ${{ github.actor }}
-        password: ${{ secrets.GITHUB_TOKEN }}
-    
-    # - name: Setup Bella Baxter
-    #   uses: cosmic-chimps/bella-baxter-setup-action@v0.1.1-preview.88
+      - name: Checkout del código
+        uses: actions/checkout@v4
 
+      - name: Login en GitHub Container Registry
+        uses: docker/login-action@v3
+        with:
+          registry: ghcr.io
+          username: ${{ github.actor }}
+          password: ${{ secrets.GITHUB_TOKEN }}
 
-    
-    - name: Build and push Docker image
-      uses: docker/build-push-action@v5
-      with:
-        context: .
-        push: true
-        # Asegúrate de que el nombre del owner (tu usuario) esté en minúsculas
-        tags: ghcr.io/garciafah/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
-        build-args: |
-          BELLA_BAXTER_API_KEY=${{ secrets.BELLA_BAXTER_API_KEY }}
+      - name: Setup Bella Baxter
+        uses: cosmic-chimps/bella-baxter-setup-action@v0.1.1-preview.88
+        with:
+          oidc: true
 
-      
-    # Notifica a dokploy para que deploye la nueva imagen
-    - name: Notificar a Dokploy (Trigger Deploy)
-      run: |
-        response=$(curl -s -o /dev/null -w "%{http_code}" -X POST ${{ secrets.DOKPLOY_WEBHOOK_URL }})
-        if [ "$response" -ne 200 ]; then
-          echo "Error al notificar con Dokploy"
-          exit 1
-        fi
-          echo "Dokploy notificado con éxito. Despliegue en curso."
+      - name: Build and push Docker image
+        uses: docker/build-push-action@v5
+        with:
+          context: .
+          push: true
+          # Asegúrate de que el nombre del owner (tu usuario) esté en minúsculas
+          tags: ghcr.io/garciafah/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
+          # env.BELLA_API_KEY comes from `Setup Bella Baxter`
+          secrets: |
+            BELLA_BAXTER_API_KEY=${{ env.BELLA_API_KEY }}
+
+      # Notifica a dokploy para que deploye la nueva imagen
+      - name: Notificar a Dokploy (Trigger Deploy)
+        run: |
+          response=$(curl -s -o /dev/null -w "%{http_code}" -X POST ${{ secrets.DOKPLOY_WEBHOOK_URL }})
+          if [ "$response" -ne 200 ]; then
+            echo "Error al notificar con Dokploy"
+            exit 1
+          fi
+            echo "Dokploy notificado con éxito. Despliegue en curso."
